# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from .googlemapsresultplaces import GoogleMapsResultPlaces, GoogleMapsResultPlacesParam
from .sourceflagginguri import SourceFlaggingURI, SourceFlaggingURITypedDict
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GoogleMapsResultTypedDict(TypedDict):
    r"""The result of the Google Maps."""

    places: NotRequired[List[GoogleMapsResultPlacesParam]]
    widget_context_token: NotRequired[str]
    source_flagging_uris: NotRequired[List[SourceFlaggingURITypedDict]]
    r"""Output only. A list of URIs that can be used to flag a place or review for
    inappropriate content. This field is populated only when the grounding
    source is Google Maps.
    """


class GoogleMapsResult(BaseModel):
    r"""The result of the Google Maps."""

    places: Optional[List[GoogleMapsResultPlaces]] = None

    widget_context_token: Optional[str] = None

    source_flagging_uris: Optional[List[SourceFlaggingURI]] = None
    r"""Output only. A list of URIs that can be used to flag a place or review for
    inappropriate content. This field is populated only when the grounding
    source is Google Maps.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["places", "widget_context_token", "source_flagging_uris"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
