# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# pyformat: disable

"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .. import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SourceFlaggingURITypedDict(TypedDict):
    r"""A URI that can be used to flag a place or review for inappropriate
    content. This is populated only when the grounding source is Google Maps.
    """

    source_id: NotRequired[str]
    r"""The ID of the place or review."""
    flag_content_uri: NotRequired[str]
    r"""The URI that can be used to flag the content."""


class SourceFlaggingURI(BaseModel):
    r"""A URI that can be used to flag a place or review for inappropriate
    content. This is populated only when the grounding source is Google Maps.
    """

    source_id: Optional[str] = None
    r"""The ID of the place or review."""

    flag_content_uri: Optional[str] = None
    r"""The URI that can be used to flag the content."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["source_id", "flag_content_uri"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
